name: Publish uid-generator to Maven Central
env:
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8

on:
  push:
    tags:
      - "v*"  # 仅在推送 tag 时触发（如 v1.0.0）

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史（用于生成版本号）

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup GPG
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          # 导入 GPG 私钥
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          # 配置信任级别
          echo "trust-model tofu" >> ~/.gnupg/gpg.conf
          echo "tofu-default-policy good" >> ~/.gnupg/gpg.conf

      - name: Deploy to Central Portal
        env:
          CENTRAL_TOKEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          CENTRAL_TOKEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
        run: |
          mvn install -DskipTests \
            --settings ./.github/maven/settings.xml \
          -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
          
          cd uid-generator  # 进入子模块目录
          mvn -B -X clean deploy -Dmaven.test.skip=true \
            --settings ../.github/maven/settings.xml \
          -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}